name: apn_analytics
description: A new Appnormal flutter package that wraps firebase analytics.
version: 2.0.0
homepage: https://github.com/appnormal/apn_analytics

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^7.1.1
  get_it: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
